image: node:12

cache:
  paths:
    - node_modules/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - install
  - lint
  - build

lint:
  stage: lint
  script:
    - npm run lint

install:
  stage: install
  script:
    - npm config get registry 
    - npm config set registry http://172.16.111.21:8088/nexus/repository/angular8-group-npm/
    - npm config get registry 
    - npm --loglevel info install

build:
  stage: build
  script:
    - npm run ci
    - ls
    - cd dist/
    - ls
